[project]
name = "qcpAPI"
version = "0.2.0"
description = ''
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools.package-data]
server_external= ["*.ico"] # add favicon icon that lives under server_internal subfolder
# [project.scripts]
# "qcp_server_start.py" = "qcpAPI.bin.server:main"
[tool.setuptools]
script-files = ["bin/qcp_server.py"]

