[project]
name = "qcpAPI"
version = "0.3.1"
description = ''
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.setuptools.package-data]
# [project.scripts]
# "qcp_server_start.py" = "qcpAPI.bin.server:main"
server_external= ["*.ico"] # add favicon icon that lives under server_internal subfolder

[tool.setuptools]
script-files = ["bin/qcp_server.py", 'bin/qcp_export_envo.py']

[tool.setuptools_scm]
# version_scheme = "post-release"
# local_scheme = "dirty-tag"
# Make a version file (can the be used by this very package)
version_file = "src/qcpAPI/_version.py"

# Use setuptools_scm pip package (auto bumps branches)
# see https://pypi.org/project/setuptools-scm/
[build-system]
requires = ["setuptools>=80", "wheel", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"


