#!/usr/bin/env bash
# Auto-generated clone script — do NOT edit by hand.
# Generated by /home/bruno/0_Software/miniconda3/envs/qcpAPI_newver/lib/python3.11/site-packages/qcp_versioning/package_docu.py at 2026-03-31T23:35:06.369054+01:00
set -euo pipefail

git clone git@github.com:bruno-von-bruening/run_psi4.git run_psi4_7854eccc4 && git -C run_psi4_7854eccc4/ checkout 7854eccc4&& \ 
cd run_psi4_7854eccc4/ && conda env create -f install/run_psi4_env.yaml -n run_psi4
