name: macOS Python + Conda CI

on:
  workflow_dispatch:  # manual runs
  push:
    #  branches: [ main , CI_explore_2 ]
  pull_request:


jobs:
    test-macos:
        runs-on: macos-14
        # env:
        #   QCPAPI_HOME: ${{ github.workspace }}

        steps:
          - name: Checkout repo
            uses: actions/checkout@v4
            with:
              fetch-depth: 1

          - name: Build env files with HTTPS + PAT for CI
            shell: bash
            run: |
              sed 's#git+ssh://git@github.com/#git+https://github.com/#g' install/qcpAPI_env.yaml > install/qcpAPI_env_ci.yaml
              sed 's#git+ssh://git@github.com/#git+https://github.com/#g' install/clone_run_psi4.sh > install/clone_run_psi4_ci.sh

          - name: Authenticate git for private dependencies
            shell: bash
            run: |
              git config --global url."https://${{ secrets.GH_PAT }}:@github.com/".insteadOf "https://github.com/"
          
          - name: install conda package for cloning with HTTPS + PAT for CI
            shell: bash -el {0}
            run: cd install && bash clone_run_psi4_ci.sh 

          - name: Install Miniconda
            uses: conda-incubator/setup-miniconda@v3
            with:
              auto-update-conda: true
              activate-environment: test_env
              environment-file: install/qcpAPI_env_ci.yaml


          - name: Run test script
            shell: bash -el {0}
            run: |
              cd tests/molpol_run
              python test.py
